In [5]:
import tensorflow as tf
import tensorflow_datasets as tfds
import os
import datetime

In [2]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [3]:
tf.__version__

'2.1.0'

In [4]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
dataset, info = tfds.load('amazon_us_reviews/Mobile_Electronics_v1_00', with_info=True)


Shuffling and writing examples to C:\/Users/Abhishek Maity/tensorflow_datasets/amazon_us_reviews/Mobile_Electronics_v1_00/0.1.0.incomplete61DG4Z/amazon_us_reviews-train.tfrecord


Dataset amazon_us_reviews downloaded and prepared to C:\Users\Abhishek Maity\tensorflow_datasets\amazon_us_reviews\Mobile_Electronics_v1_00\0.1.0. Subsequent calls will reuse this data.


In [7]:
info

tfds.core.DatasetInfo(
    name='amazon_us_reviews',
    version=0.1.0,
    description='Amazon Customer Reviews (a.k.a. Product Reviews) is one of Amazons iconic products. In a period of over two decades since the first review in 1995, millions of Amazon customers have contributed over a hundred million reviews to express opinions and describe their experiences regarding products on the Amazon.com website. This makes Amazon Customer Reviews a rich source of information for academic researchers in the fields of Natural Language Processing (NLP), Information Retrieval (IR), and Machine Learning (ML), amongst others. Accordingly, we are releasing this data to further research in multiple disciplines related to understanding customer product experiences. Specifically, this dataset was constructed to represent a sample of customer evaluations and opinions, variation in the perception of a product across geographical regions, and promotional intent or bias in reviews.

Over 130+ million cus

In [8]:
dataset

{'train': <PrefetchDataset shapes: {data: {customer_id: (), helpful_votes: (), marketplace: (), product_category: (), product_id: (), product_parent: (), product_title: (), review_body: (), review_date: (), review_headline: (), review_id: (), star_rating: (), total_votes: (), verified_purchase: (), vine: ()}}, types: {data: {customer_id: tf.string, helpful_votes: tf.int32, marketplace: tf.string, product_category: tf.string, product_id: tf.string, product_parent: tf.string, product_title: tf.string, review_body: tf.string, review_date: tf.string, review_headline: tf.string, review_id: tf.string, star_rating: tf.int32, total_votes: tf.int32, verified_purchase: tf.int64, vine: tf.int64}}>}

In [13]:
train_dataset = dataset['train']

In [12]:
dataset.keys()

dict_keys(['train'])

In [14]:
print(train_dataset)

<PrefetchDataset shapes: {data: {customer_id: (), helpful_votes: (), marketplace: (), product_category: (), product_id: (), product_parent: (), product_title: (), review_body: (), review_date: (), review_headline: (), review_id: (), star_rating: (), total_votes: (), verified_purchase: (), vine: ()}}, types: {data: {customer_id: tf.string, helpful_votes: tf.int32, marketplace: tf.string, product_category: tf.string, product_id: tf.string, product_parent: tf.string, product_title: tf.string, review_body: tf.string, review_date: tf.string, review_headline: tf.string, review_id: tf.string, star_rating: tf.int32, total_votes: tf.int32, verified_purchase: tf.int64, vine: tf.int64}}>


In [15]:
len(list(train_dataset))

104975

In [24]:
BUFFER_SIZE = 30000 # Data that we want to prefetch
BATCH_SIZE = 128

In [25]:
train_dataset.shuffle(BUFFER_SIZE, reshuffle_each_iteration=False)

<ShuffleDataset shapes: {data: {customer_id: (), helpful_votes: (), marketplace: (), product_category: (), product_id: (), product_parent: (), product_title: (), review_body: (), review_date: (), review_headline: (), review_id: (), star_rating: (), total_votes: (), verified_purchase: (), vine: ()}}, types: {data: {customer_id: tf.string, helpful_votes: tf.int32, marketplace: tf.string, product_category: tf.string, product_id: tf.string, product_parent: tf.string, product_title: tf.string, review_body: tf.string, review_date: tf.string, review_headline: tf.string, review_id: tf.string, star_rating: tf.int32, total_votes: tf.int32, verified_purchase: tf.int64, vine: tf.int64}}>

In [26]:
for reviews in train_dataset.take(2):
    print(reviews)

{'data': {'customer_id': <tf.Tensor: shape=(), dtype=string, numpy=b'20980074'>, 'helpful_votes': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'marketplace': <tf.Tensor: shape=(), dtype=string, numpy=b'US'>, 'product_category': <tf.Tensor: shape=(), dtype=string, numpy=b'Mobile_Electronics'>, 'product_id': <tf.Tensor: shape=(), dtype=string, numpy=b'B00D1847NE'>, 'product_parent': <tf.Tensor: shape=(), dtype=string, numpy=b'274617424'>, 'product_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Teenage Mutant Ninja Turtles Boombox CD Player with Text Display, AM/FM Stereo Radio, Repeat Function'>, 'review_body': <tf.Tensor: shape=(), dtype=string, numpy=b'Does not work'>, 'review_date': <tf.Tensor: shape=(), dtype=string, numpy=b'2015-01-09'>, 'review_headline': <tf.Tensor: shape=(), dtype=string, numpy=b'One Star'>, 'review_id': <tf.Tensor: shape=(), dtype=string, numpy=b'R1OVS0D6SEXPW7'>, 'star_rating': <tf.Tensor: shape=(), dtype=int32, numpy=1>, 'total_votes': <tf.Tensor: shape=(

In [28]:
for reviews in train_dataset.take(10):
    review_text = reviews['data']
    print(review_text.get('review_body').numpy())
    print(review_text.get('star_rating'))
    print(tf.where(review_text.get('star_rating')>3, 1, 0).numpy())

b'Does not work'
tf.Tensor(1, shape=(), dtype=int32)
0
b'This is a great wiring kit i used it to set up my Pyle 2000 watt amp to 2 alpine subs and worked just fine. im not sure about the power cord and its length because my battery is in the back but the ground cord is a bit short and thats its only flaw and that why i gave it 4 stars. great kit'
tf.Tensor(4, shape=(), dtype=int32)
1
b'It works great so much faster than USB charger..Buy it! You will be glad you did!'
tf.Tensor(5, shape=(), dtype=int32)
1
b'This product was purchased to hold a monitor on a desk, which is connected to a security camera at a door of our business. It serves our purpose perfectly.'
tf.Tensor(5, shape=(), dtype=int32)
1
b"it works but it has really bad sound quality. the bass doesn't work almost at all"
tf.Tensor(3, shape=(), dtype=int32)
0
b"Excellent product !!!<br />Easy to install and performs flawlessly.<br />Video and audio is clear and GPS map pinpoints the exact vehicle location.<br />I'm thinking of

In [33]:
tokenizer = tfds.deprecated.text.Tokenizer()

vocabulary_set = set()
for _, reviews in train_dataset.enumerate():
    review_text = reviews['data']
    reviews_tokens = tokenizer.tokenize(review_text.get('review_body').numpy())
    vocabulary_set.update(reviews_tokens)
vocab_size = len(vocabulary_set)
vocab_size
    


73738

In [34]:
encoder = tfds.deprecated.text.TokenTextEncoder(vocabulary_set)

In [35]:
print(vocabulary_set)

{'Subpart', 'HomeDock', 'movin', 'detaching', 'thinkpad', 'reacts', 'AV2', 'scolded', 'actors', 'Ordner', 'claws', 'systemXR400', 'Godzilla', 'Freestyle', 'happenes', 'chevy', 'Foldable', 'developmentally', 'mech', '7D', 'quibble', 'virtues', 'expectative', 'prodotto', 'photograph', 'Duck', 'workplace', 'honest', 'descriptived', 'hemp', 'B0057QV81W', 'throat', 'artwork', 'Atrix', '44B4B', 'capaccity', 'Pofung', 'primeros', 'Equipment', 'OBCON', 'navigated', 'abnormally', 'roly', 'arrangement', 'theX', 'TELEFONO', 'known', 'standered', 'Restore', 'Pristine', 'halogen', 'buffet', 'unsecurely', 'Dwarf', 'invokes', 'LUV', 'flasher', 'UNITED', 'Nada', 'AINT', 'Taiwanese', 'chunk', 'jarred', 'selling', 'Stand', 'Inconsistent', 'happiness', 'signed', 'Linking', 'SMOOSHED', 'RESPONDED', 'DAF', 'AppRadioTM', 'Mehh', 'duh', 'hz', 'DIFICULTAR', 'line', '2mo', 'Sidekick', 'skin', 'jolting', '94A', 'whis', 'intervals', 'testify', 'Audiobahn', 'magpul', '1600w', 'inch', 'tailored', 'planning', 'av42